name: al-insaf-ngo
services:
- name: web
  github:
    repo: roneox26/Al-insaf
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt && python create_db.py
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 120 app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: FLASK_ENV
    value: production
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
databases:
- name: db
  engine: PG
  version: "12"
